name: go-test
on: [push]
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: install gotip
        run: go install golang.org/dl/gotip@latest && gotip download
      - name: test
        run: gotip test ./...
