name: gotip-test
on: [push]
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: pull gotip image
        run: docker pull nobishino/gotip
      - name: test
        run: docker run --volume `pwd`:/src nobishino/gotip /bin/bash -c "gotip test ./..."
